# Generated by Django 2.1.7 on 2019-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom_table',
            fields=[
                ('crid', models.IntegerField(primary_key=True, serialize=False, verbose_name='实验室号')),
                ('crname', models.CharField(max_length=20, verbose_name='实验室名')),
                ('crsize', models.SmallIntegerField(choices=[(0, '小'), (1, '中'), (2, '大'), (3, '超大')], default=0, verbose_name='实验室规格')),
                ('crdevice', models.IntegerField(default=0, verbose_name='设备个数')),
            ],
            options={
                'verbose_name': '实验室',
                'db_table': 't_classroom',
            },
        ),
    ]
