# Generated by Django 2.1.7 on 2019-04-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher_table',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False, verbose_name='教师工号')),
                ('tname', models.CharField(max_length=20, verbose_name='教师名')),
            ],
            options={
                'verbose_name': '教师表',
                'db_table': 't_teacher',
            },
        ),
    ]
