# Generated by Django 2.1.7 on 2019-05-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0002_lesson_table_lteacher'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_attendance_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('astime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('asstatus', models.SmallIntegerField(choices=[(1, '全勤'), (2, '迟到'), (3, '早退'), (4, '缺勤'), (5, '请假')], default=1, verbose_name='考勤信息')),
                ('alesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson_table', verbose_name='课程')),
                ('asuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student_table', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生考勤',
                'db_table': 't_s_attendance',
            },
        ),
        migrations.CreateModel(
            name='teacher_attendance_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('atstatus', models.SmallIntegerField(choices=[(1, '全勤'), (2, '迟到'), (3, '早退'), (4, '缺勤'), (5, '请假')], default=1, verbose_name='考勤信息')),
                ('alesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson_table', verbose_name='课程')),
                ('atuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher_table', verbose_name='教师')),
            ],
            options={
                'verbose_name': '教师考勤',
                'db_table': 't_t_attendance',
            },
        ),
    ]
