# Generated by Django 2.1.7 on 2019-05-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_attendance_table',
            fields=[
                ('asid', models.IntegerField(primary_key=True, serialize=False, verbose_name='考勤id')),
                ('astime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('asstatus', models.SmallIntegerField(choices=[(1, '全勤'), (2, '迟到'), (3, '早退'), (4, '缺勤'), (5, '请假')], default=1, verbose_name='考勤信息')),
            ],
            options={
                'verbose_name': '学生考勤',
                'db_table': 't_s_attendance',
            },
        ),
        migrations.CreateModel(
            name='teacher_attendance_table',
            fields=[
                ('atid', models.IntegerField(primary_key=True, serialize=False, verbose_name='考勤id')),
                ('attime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('atstatus', models.SmallIntegerField(choices=[(1, '全勤'), (2, '迟到'), (3, '早退'), (4, '缺勤'), (5, '请假')], default=1, verbose_name='考勤信息')),
            ],
            options={
                'verbose_name': '教师考勤',
                'db_table': 't_t_attendance',
            },
        ),
    ]
