# Generated by Django 2.1.7 on 2019-05-09 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lesson', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_table',
            name='lteacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher_table', verbose_name='课程老师'),
        ),
    ]
